name: Python package

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox

      - name: Run tests
        run: |
          pip install .[test]
          pytest

      - name: Build package
        run: |
          pip install --upgrade build
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            repository-url: https://upload.pypi.org/legacy/
            packages-dir: dist/
            skip-existing: true
            verbose: true

      - name: Publish package to PyPI Invoker
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: alpha
            password: ${{ secrets.ALPHA_PYPI_API_TOKEN }}
            repository-url: https://pypi.piesource.cn/alpha/private/
            packages-dir: dist/
            skip-existing: true
            verbose: true